global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rest-service'
    scrape_protocols: ['PrometheusText0.0.4', 'OpenMetricsText1.0.0']
    static_configs:
      - targets: ['rest-service:5000']
    metrics_path: '/metrics'

  - job_name: 'grpc-service'
    scrape_protocols: ['PrometheusText0.0.4', 'OpenMetricsText1.0.0']
    static_configs:
      - targets: ['grpc-service:9103']
    metrics_path: '/metrics'
